# Setup
title: JBoss Middleware Workshops
tagline: > # this means to ignore newlines until "description:"
  Don't just read about what JBoss Middleware can do — try
  it for yourself with these workshops!
description: > # this means to ignore newlines until "baseurl:"
  Create, discover, and access content for JBoss Middleware
  by Red Hat.
baseurl: "/jboss-workshops" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
paginate: 1

# About/contact
author:
  name: Michael Surbey
  vocation: Cloud Solutions Architect
  email: msurbey@redhat.com
  github_username:  ecwpz91
  twitter_username: ecwpz91
  # url:  http://yourhomepage.com

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-paginate
  - jemoji

# Exclude
exclude:
   - Gemfile
   - jekyll-cayman-theme.gemspec

# Local server port
port: 4000

# Local server hostname
host: 0.0.0.0
